/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#191f31",
        "tertiary-container": "#00a572",
        "secondary-container": "#03b5d3",
        "surface-variant": "#2e3447",
        "on-surface-variant": "#cbc3d7",
        background: "#0c1324",
        "primary-container": "#a078ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#070d1f",
        "surface-container-high": "#23293c",
        "inverse-on-surface": "#2a3043",
        "tertiary-fixed-dim": "#4edea3",
        tertiary: "#4edea3",
        secondary: "#4cd7f6",
        "on-primary-fixed": "#23005c",
        "on-tertiary-container": "#00311f",
        "primary-fixed": "#e9ddff",
        "on-secondary-fixed-variant": "#004e5c",
        "inverse-surface": "#dce1fb",
        "secondary-fixed": "#acedff",
        "surface-container-highest": "#2e3447",
        outline: "#958ea0",
        "on-secondary-fixed": "#001f26",
        "surface-tint": "#d0bcff",
        error: "#ffb4ab",
        "inverse-primary": "#6d3bd7",
        "on-primary-fixed-variant": "#5516be",
        "on-tertiary": "#003824",
        "on-background": "#dce1fb",
        "secondary-fixed-dim": "#4cd7f6",
        primary: "#d0bcff",
        "on-primary-container": "#340080",
        "surface-container-low": "#151b2d",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary-container": "#00424e",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003640",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#002113",
        "surface-bright": "#33394c",
        surface: "#0c1324",
        "on-surface": "#dce1fb",
        "outline-variant": "#494454",
        "on-error": "#690005",
        "surface-dim": "#0c1324",
        "on-primary": "#3c0091",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Geist", "sans-serif"],
        display: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        unit: "4px",
        "container-max": "1440px",
        gutter: "24px",
        margin: "32px",
      },
    },
  },
  plugins: [],
};




